### ISSUE TITLE
pipeline.exceptions.CompressorError

### ISSUE THREAD

**Issue by ErikEvenson** [cyberdelia/django-pipeline#318]
I occasionally (once every 10 runs or so?) get this error when django-pipeline is compressing my JS:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/VBEZ/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/VBEZ/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/VBEZ/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/.virtualenvs/VBEZ/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/VBEZ/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/home/vagrant/.virtualenvs/VBEZ/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 173, in handle_noargs
    collected = self.collect()
  File "/home/vagrant/.virtualenvs/VBEZ/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 118, in collect
    for original_path, processed_path, processed in processor:
  File "/home/vagrant/.virtualenvs/VBEZ/local/lib/python2.7/site-packages/pipeline/storage.py", line 39, in post_process
    packager.pack_javascripts(package)
  File "/home/vagrant/.virtualenvs/VBEZ/local/lib/python2.7/site-packages/pipeline/packager.py", line 110, in pack_javascripts
    return self.pack(package, self.compressor.compress_js, js_compressed, templates=package.templates, **kwargs)
  File "/home/vagrant/.virtualenvs/VBEZ/local/lib/python2.7/site-packages/pipeline/packager.py", line 104, in pack
    content = compress(paths, **kwargs)
  File "/home/vagrant/.virtualenvs/VBEZ/local/lib/python2.7/site-packages/pipeline/compressors/__init__.py", line 65, in compress_js
    js = getattr(compressor(verbose=self.verbose), 'compress_js')(js)
  File "/home/vagrant/.virtualenvs/VBEZ/local/lib/python2.7/site-packages/pipeline/compressors/yuglify.py", line 13, in compress_js
    return self.compress_common(js, 'js', settings.PIPELINE_YUGLIFY_JS_ARGUMENTS)
  File "/home/vagrant/.virtualenvs/VBEZ/local/lib/python2.7/site-packages/pipeline/compressors/yuglify.py", line 10, in compress_common
    return self.execute_command(command, content)
  File "/home/vagrant/.virtualenvs/VBEZ/local/lib/python2.7/site-packages/pipeline/compressors/__init__.py", line 237, in execute_command
    raise CompressorError(stderr)
pipeline.exceptions.CompressorError: Killed
```

The only way I have found to continue is to restart the vagrant box that I am developing on.

**Comment by DFieldFL** [comment]
I just wanted to update that this is still happening in pipline v1.4.3 and yuglify v0.1.4. Switched to https://github.com/mishoo/UglifyJS2/ for the mean time.

**Comment by ErikEvenson** [comment]
For what it is worth, I'm running pipeline 1.3.23 and yuglify 0.1.4 and haven't seen the error in a long time.  Guess I should look into upgrading to 1.4 sometime...

**Comment by cyberdelia** [comment]
Closing as it seems to be resolved.

**Comment by thanos** [comment]
Still open
python2.7

django-pipeline==1.5.0    
Django==1.8.1 
yuglify@0.1.4 

Crashing is normal but some decent error hanlding would be good.

**Comment by cpury** [comment]
Also still seeing this in 1.5.4
