### ISSUE TITLE
CompilerError: Warning. Error encountered while reading cache ./.sass-cache/YYY/XXX.scssc: end of file reached

### ISSUE THREAD

**Issue by cameel** [cyberdelia/django-pipeline#420]
I have recently upgraded from django-pipeline 1.3.25 to 1.4.5 and I'm getting `CompilerError`s both in `collectstatic` and when rendering the pages in development:
```
pipeline.exceptions.CompilerError: Warning. Error encountered while reading cache ./.sass-cache/9cd8cf35b80516a0fdc8eda38af73683245e3a0b/_scaffolding.scssc: end of file reached
```
The errors are not persistent - they go away when I refresh/rerun, seemingly without any breakage and do not happen again until I clear my `STATIC_ROOT`. For example `collectstatic` fails twice and after that always succeeds.

The file mentioned in the message varies. I've seen for example `_nowrap.scssc`, `_hover-link.scssc`, `_inline-block.scssc` or `_ellipsis.scssc`. These are definitely not my files. They're not the files being preprocessed. I guess they must be a part of Compass or Bootstrap. The file being preprocessed when it fails never includes any of them directly though it may be including them indirectly through something from Compass.

File being preprocessed also varies. `collectstatic` seems to do the preprocessing in random order but it's also not just first or n-th file being preprocessed. It looks like it can fail randomly for any of my files.

The command that pipeline runs when it happens looks like this:

``` bash
/usr/bin/env sass --compass somefile.sass somefile.css
```

I tried running it manually on all my `.sass` files and it does not fail or even produce any output (`cm/public` is my `STATIC_ROOT`):
```
./manage.py collectstatic --no-post-process
cd cm/public
find . -name '*.sass' -exec /usr/bin/env sass --compass {} {}.css \;
```

Adding `--no-cache` to `PIPELINE_SASS_ARGUMENTS` makes the problem go away. It's just a workaround since it probably makes recompilation slower in development.

I don't think it's a problem with sass. The compilation works fine with django-pipeline 1.3.25 and the same version of sass (3.2.10). I also checked django-pipeline 1.4.2 earlier (the one that was putting assets in `/tmp`) and it was affected by this problem too.

I'm not running multiple compilations in parallel or `sass --watch` so this is definitely not the problem. I does look like a race condition though. Is sass or django-pipeline doing any part of the precompilation in parallel threads?

**Comment by cameel** [comment]
Stack trace:

``` python
Traceback (most recent call last):
  File "cm/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 173, in handle_noargs
    collected = self.collect()
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 119, in collect
    for original_path, processed_path, processed in processor:
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/pipeline/storage.py", line 29, in post_process
    packager.pack_stylesheets(package)
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/pipeline/packager.py", line 96, in pack_stylesheets
    variant=package.variant, **kwargs)
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/pipeline/packager.py", line 105, in pack
    paths = self.compile(package.paths, force=True)
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/pipeline/packager.py", line 99, in compile
    return self.compiler.compile(paths, force=force)
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/pipeline/compilers/__init__.py", line 56, in compile
    return list(executor.map(_compile, paths))
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/concurrent/futures/_base.py", line 580, in map
    yield future.result()
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/pipeline/compilers/__init__.py", line 41, in _compile
    outdated=outdated, force=force)
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/pipeline/compilers/sass.py", line 22, in compile_file
    return self.execute_command(command, cwd=dirname(infile))
  File "/home/cameel/.virtualenvs/test/lib/python2.7/site-packages/pipeline/compilers/__init__.py", line 102, in execute_command
    raise CompilerError(stderr)
pipeline.exceptions.CompilerError: Warning. Error encountered while reading cache ./.sass-cache/9cd8cf35b80516a0fdc8eda38af73683245e3a0b/_scaffolding.scssc: end of file reached
```

**Comment by cameel** [comment]
I have upgraded to sass 3.4.12, compass 1.0.3 and I'm no longer getting this error. Looks like the newer versions are less prone to race conditions.

So django-pipeline should either not try to run earlier versions in parallel or state clearly in the docs that these versions are not supported...

**Comment by cyberdelia** [comment]
Unfortunately, there are way too many sass implementation out there that it's nearly impossible to filter by version or anything else.
