### ISSUE TITLE
Collectstatic doesn't find compiled css with s3boto storage

### ISSUE THREAD

**Issue by jplehmann** [cyberdelia/django-pipeline#486]
Testing locally, with `PIPELINE_ENABLED = True`, with s3 boto storage, when I run `collectstatic` it fails to find the compiled css. However, after the failed command, I can see that the css *has* been generated and is in my source tree alongside the `.less` files (`mysite/static/css/xxx.css`).   But it appears that `concatenate_and_rewrite` is looking for the compiled s3 remotely on s3.

(When I run the command again it finds that one, then fails on the next one in the same fashion. But this is only because the locally compiled css is copied to s3, so this beside the point).

Would also love to see those files being generated in another dir, as discussed in issue [202](https://github.com/cyberdelia/django-pipeline/issues/202#issuecomment-126347710).

Using django pipeline 1.5.2 with s3boto storage and LESS compiler.

```
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'pipeline.finders.PipelineFinder',

STATICFILES_LOCATION = 'static'

class S3PipelineManifestStorage(PipelineMixin, ManifestFilesMixin, S3BotoStorage):
    location = settings.STATICFILES_LOCATION
```

The error:
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
    collected = self.collect()
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    for original_path, processed_path, processed in processor:
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/pipeline/storage.py", line 26, in post_process
    packager.pack_stylesheets(package)
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/pipeline/packager.py", line 96, in pack_stylesheets
    variant=package.variant, **kwargs)
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/pipeline/packager.py", line 106, in pack
    content = compress(paths, **kwargs)
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/pipeline/compressors/__init__.py", line 73, in compress_css
    css = self.concatenate_and_rewrite(paths, output_filename, variant)
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/pipeline/compressors/__init__.py", line 137, in concatenate_and_rewrite
    content = self.read_text(path)
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/pipeline/compressors/__init__.py", line 216, in read_text
    content = self.read_bytes(path)
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/pipeline/compressors/__init__.py", line 210, in read_bytes
    file = staticfiles_storage.open(path)
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/django/core/files/storage.py", line 37, in open
    return self._open(name, mode)
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/storages/backends/s3boto.py", line 366, in _open
    raise IOError('File does not exist: %s' % name)
IOError: File does not exist: static/css/mystyles.css
```

**Comment by jplehmann** [comment]
More details were added. Any ideas @cyberdelia?

**Comment by jplehmann** [comment]
I now realize this is a duplicate of #473 and will continue conversation there.
