### ISSUE TITLE
error with yuglify collectstatic ?

### ISSUE THREAD

**Issue by TurBoss** [cyberdelia/django-pipeline#489]
I'm having this error when running collectstatic
any ideas?
if this issue is not related to django-pipeline plz close thx

jauria@jauria-studio:~/Proyectos/homeAutomation$ ./manage.py collectstatic 

You have requested to collect static files at the destination
location as specified in your settings:

    /home/jauria/Proyectos/homeAutomation/static_files

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Post-processed 'controlPanel/css/main.css' as 'controlPanel/css/main.css'
Post-processed 'controlPanel/js/main.js' as 'controlPanel/js/main.js'
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
    collected = self.collect()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    for original_path, processed_path, processed in processor:
  File "/usr/local/lib/python2.7/dist-packages/pipeline/storage.py", line 33, in post_process
    packager.pack_javascripts(package)
  File "/usr/local/lib/python2.7/dist-packages/pipeline/packager.py", line 112, in pack_javascripts
    return self.pack(package, self.compressor.compress_js, js_compressed, templates=package.templates, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipeline/packager.py", line 106, in pack
    content = compress(paths, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipeline/compressors/__init__.py", line 67, in compress_js
    js = getattr(compressor(verbose=self.verbose), 'compress_js')(js)
  File "/usr/local/lib/python2.7/dist-packages/pipeline/compressors/yuglify.py", line 13, in compress_js
    return self.compress_common(js, 'js', settings.PIPELINE_YUGLIFY_JS_ARGUMENTS)
  File "/usr/local/lib/python2.7/dist-packages/pipeline/compressors/yuglify.py", line 10, in compress_common
    return self.execute_command(command, content)
  File "/usr/local/lib/python2.7/dist-packages/pipeline/compressors/__init__.py", line 244, in execute_command
    raise CompressorError(stderr)
pipeline.exceptions.CompressorError: 
/usr/local/lib/node_modules/yuglify/bin/yuglify:77
                throw(err);
                      ^
Error
    at new JS_Parse_Error (/usr/local/lib/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:263:18)
    at js_error (/usr/local/lib/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:271:11)
    at croak (/usr/local/lib/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:733:9)
    at token_error (/usr/local/lib/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:740:9)
    at unexpected (/usr/local/lib/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:746:9)
    at /usr/local/lib/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1112:13
    at maybe_unary (/usr/local/lib/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1209:19)
    at expr_ops (/usr/local/lib/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1236:24)
    at maybe_conditional (/usr/local/lib/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1240:20)
    at maybe_assign (/usr/local/lib/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1264:20)
    at /usr/local/lib/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1278:20
    at vardefs (/usr/local/lib/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1065:32)
    at var_ (/usr/local/lib/node_modules/yuglify/node_modules/uglify-js/lib/parse-js.js:1077:26)

**Comment by TurBoss** [comment]
I noticed that this only happends whit jquery.js in vendor group

**Comment by TurBoss** [comment]
sry forgot about
PIPELINE_ENABLED = True
